# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UK_Police_APIDialog
                                 A QGIS plugin
 This plugin connect Qgis to UK Police API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-24
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Sayeh Omar 
        email                : sayehomar@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from .Logic import calculator
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "UK Police API_dialog_base.ui")
)


class UK_Police_APIDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(UK_Police_APIDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.BB_calcul.clicked.connect(self.on_calcul)

    def on_calcul(self):
        # Get the values from the spin boxes
        Value_A = self.SB1.value()
        Value_B = self.SB2.value()
        # Create an instance of the calculator class
        calc = calculator(Value_A, Value_B)

        # Call the calcul method to get the result
        result = calc.calcul()
        print(f"results:{result}")
